// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuWk0xBqaW1qKiNcPo48KwhcoFhMocB0',
    appId: '1:145195283796:web:d44e74a8b814121112c4c1',
    messagingSenderId: '145195283796',
    projectId: 'rentboat2-7e150',
    authDomain: 'rentboat2-7e150.firebaseapp.com',
    storageBucket: 'rentboat2-7e150.firebasestorage.app',
    measurementId: 'G-B8EGH01V43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBykzJe84XzBLnigObKSC47MPdQUGKjDLQ',
    appId: '1:145195283796:android:8d7e49d60c0ed82712c4c1',
    messagingSenderId: '145195283796',
    projectId: 'rentboat2-7e150',
    storageBucket: 'rentboat2-7e150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaD2Jp48z7qvI1PRlJJ13lWKSoA3pAnpk',
    appId: '1:145195283796:ios:45269bb765b834b912c4c1',
    messagingSenderId: '145195283796',
    projectId: 'rentboat2-7e150',
    storageBucket: 'rentboat2-7e150.firebasestorage.app',
    iosClientId:
        '145195283796-fj81bui5ma3e0em1vjto3135pm0c4shu.apps.googleusercontent.com',
    iosBundleId: 'es.zaitec.oceanRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaD2Jp48z7qvI1PRlJJ13lWKSoA3pAnpk',
    appId: '1:145195283796:ios:45269bb765b834b912c4c1',
    messagingSenderId: '145195283796',
    projectId: 'rentboat2-7e150',
    storageBucket: 'rentboat2-7e150.firebasestorage.app',
    iosClientId:
        '145195283796-fj81bui5ma3e0em1vjto3135pm0c4shu.apps.googleusercontent.com',
    iosBundleId: 'es.zaitec.oceanRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQuWk0xBqaW1qKiNcPo48KwhcoFhMocB0',
    appId: '1:145195283796:web:b6df68d3bf96ae9812c4c1',
    messagingSenderId: '145195283796',
    projectId: 'rentboat2-7e150',
    authDomain: 'rentboat2-7e150.firebaseapp.com',
    storageBucket: 'rentboat2-7e150.firebasestorage.app',
    measurementId: 'G-SFFZRP99WR',
  );
}
